services:
  # Register your custom form type in the container:
  program.user.form.registration:
    class: UserBundle\Form\RegistrationFormType
    arguments:
      - '%fos_user.model.user.class%'
      - '@fos_user.user_manager'
      - '@request_stack' # we need invite code
    tags:
      - { name: "form.type", alias: "program_user_registration" }
  # overwrite fosu profile form
  program.user.form.profile:
    class: UserBundle\Form\ProfileFormType
    arguments:
      - '%fos_user.model.user.class%'
      - '@fos_user.user_manager'
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: "form.type", alias: "program_user_profile" }

  program.user.form.data_transformer.invitation:
    class: UserBundle\Form\DataTransformer\InvitationToCodeTransformer
    arguments: ['@doctrine.orm.entity_manager']
    public: false

  program.user.form.invitation:
    class: UserBundle\Form\InvitationFormType
    arguments: ['@program.user.form.data_transformer.invitation']
    tags:
      - { name: "form.type", alias: "program_invitation_type" }

  # user twig extension
  program.user.twig.extension:
    class: UserBundle\Twig\UserExtension
    tags:
      - { name: twig.extension }

  # fosuser events controller hook - registration
  program.user.registration.listener:
    class: UserBundle\EventListener\RegistrationListener
    tags:
      - { name: kernel.event_subscriber, event: fos_user.registration.initialize, method: onRegistrationInitialize }
      - { name: kernel.event_subscriber, event: fos_user.registration.success, method: onRegistrationSuccess }
    arguments:
      - '@router'
      - '@security.authorization_checker'
      - '@doctrine.orm.entity_manager'
      - '@session'

  # fosuser events controller hook - resetting password
  program.user.resetting.listener:
    class: UserBundle\EventListener\PasswordResettingListener
    tags:
      - { name: kernel.event_subscriber, event: fos_user.resetting.send_email.initialize, method: beginResettingProcess }
    arguments:
      - '@router'
      - '@session'
      - '@validator'

  # on every login
  program.user.login.listener:
    class: UserBundle\EventListener\UserLocaleListener
    arguments: ['@session']
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

  # on every request
  program.user.locale.listener:
    class: UserBundle\EventListener\LocaleListener
    arguments: ['%kernel.default_locale%']
    tags:
      - { name: kernel.event_subscriber }
  dateformat.twig.extension:
    class: UserBundle\Twig\DateFormatExtension
    tags:
      - { name: twig.extension }

  account.calendar_listener:
    class: UserBundle\EventListener\CalendarEventListener
    tags:
        - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@security.token_storage'
