services:

    _defaults:
        autowire: true
        public: false

    _instanceof:
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: ['kernel.event_subscriber']
        Symfony\Component\Form\AbstractType:
            tags: ['form.type']

    UserBundle\Service\EventSubscriber\:
        resource: '../../Service/EventSubscriber/*'

    UserBundle\Service\EventListener\CalendarListener:
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }

    UserBundle\Service\EventSubscriber:
        arguments: ['%kernel.default_locale%']

    UserBundle\Form\RegistrationFormType:
        arguments:
            - '%fos_user.model.user.class%'
            - '@fos_user.user_manager'
            - '@request_stack'

    UserBundle\Form\ProfileFormType:
        arguments:
            - '%fos_user.model.user.class%'
            - '@fos_user.user_manager'
            - '@doctrine.orm.entity_manager'

    UserBundle\Form\DataTransformer\InvitationToCodeTransformer:

    UserBundle\Form\InvitationFormType:
