services:
  dateformat.twig.extension:
    class: Wit\Program\CalendarBundle\Twig\DateFormatExtension
    tags:
      - { name: twig.extension }

  acme.demobundle.calendar_listener:
    class: Wit\Program\CalendarBundle\EventListener\CalendarEventListener
    tags:
        - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@security.token_storage'
