imports:
    - { resource: ../config.yml }
    - { resource: swiftmailer.yml }
    - { resource: hautelook_alice.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/main.log"
            level: debug
            channels: ['!event', '!php', '!doctrine']
        console:
            type:   console
            bubble: false
            channels: ['!event', '!doctrine']

services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            translations:
                driver:   pdo_mysql
                host:     "%translations_database_host%"
                port:     "%translations_database_port%"
                dbname:   "%translations_database_name%"
                user:     "%translations_database_user%"
                password: "%translations_database_password%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
