#http://a2lix.fr/bundles/translation-form/
a2lix_translation_form:
    locale_provider: Service\Form\LocaleFormProvider
    locales: [en]
    default_locale: en
    required_locales: [en]
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"
    # @TODO my own templating file
