imports:
    - { resource: parameters.yml }
    - { resource: monolog.yml }
    - { resource: doctrine.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: fos_user.yml }
    - { resource: stof_doctrine_extension.yml }
    - { resource: assetic.yml }
    - { resource: assetic_version.yml }
    - { resource: kachkaev_assets_version.yml }
    - { resource: twig.yml }
    - { resource: liip_imagine.yml }
    - { resource: vich_uploader.yml }
    - { resource: swiftmailer.yml }
    - { resource: knp_paginator.yml }
    - { resource: knp_doctrine_behaviors.yml }
    - { resource: a2lix_translation_form.yml }
    - { resource: sc_datetimepicker.yml }
    - { resource: knp_snappy.yml }
    - { resource: presta_sitemap.yml }
    - { resource: isometriks_spam.yml }
    - { resource: sensio_framework_extra.yml }
    - { resource: lexik_translation.yml }
    # - { resource: cspoo_swiftmailer_mailgun.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }
    - { resource: "@SiteBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    paginate.limit: 50
framework:
    default_locale: "%locale%" # parameters.locale
    translator: { fallback: 'en' }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
