# # https://github.com/tehplague/swiftmailer-mailgun-bundle
# cspoo_swiftmailer_mailgun:
#     key: "key-xxxxxxxxxx"
#     domain: "mydomain.com"
#     http_client: 'httplug.client' # Optional. Defaults to null and uses discovery to find client.

# # Swiftmailer Configuration
# swiftmailer:
#     transport: "mailgun"
#     spool:     { type: memory } # This will start sending emails on kernel.terminate event
