# https://github.com/lexik/LexikTranslationBundle/blob/master/Resources/doc/index.md
lexik_translation:
    # base_layout: "LexikTranslationBundle::layout.html.twig"
    base_layout: "::translationsLayout.html.twig"
    fallback_locale: [en] # (required) default locale(s) to use
    managed_locales: '%lexik_translation.managed_locales%' # (required) locales that the bundle has to manage
    storage:
        type: orm # orm | mongodb | propel
        object_manager: translations  # manager which uses different connection (see: http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html)
    exporter:
        use_yml_tree: true # to print a nice tree in the yml source files. (It is a little slower).
    grid_input_type: textarea # text|textarea
    grid_toggle_similar: false
    resources_registration:
        type: '%lexik_translation.resources_registration.type%'  # all | files | database
        managed_locales_only: true
