# http://symfony.com/doc/current/reference/configuration/monolog.html
monolog:
    # Additional Channels without Tagged Services
    channels: ['mail', 'export']
    # that creates services: monolog.logger.mail, monolog.logger.export
    handlers:
        # common for all environments
        mails:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/mails.log"
            level: debug
            channels: ['mail']
        export:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/export.log"
            level: debug
            channels: ['export']
