# sitemap
# https://github.com/prestaconcept/PrestaSitemapBundle/issues/101
# PrestaSitemapBundle:
#     resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
#     prefix: /

#------------------------------------------#
#                Main page                 #
#------------------------------------------#

landing_page:
    resource: "@LandingPageBundle/Controller/"
    type: annotation
    prefix: /
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}
    host: "{domain_name}.{domain_ext}"
    # options:
    #     sitemap:
    #         priority: 0.7
    #         changefreq: weekly

#------------------------------------------#
#         Single project homepage          #
#------------------------------------------#

# main page resources
homepage_locale:
    path: /
    prefix: /{_locale}/
    requirements:
        _locale: '%locale_possible%'
    defaults: { _controller: 'SiteBundle:Homepage:index', _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}
    host: "{subdomain}.{domain_name}.{domain_ext}"
    # options:
    #     sitemap:
    #         priority: 0.7
    #         changefreq: weekly

site_content:
    resource: "@SiteBundle/Controller/"
    type: annotation
    prefix: /{_locale}/
    requirements:
        _locale: '%locale_possible%'
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}
    host: "{subdomain}.{domain_name}.{domain_ext}"
    # options:
    #     sitemap:
    #         priority: 0.7
    #         changefreq: weekly

#------------------------------------------#
#                  User                    #
#------------------------------------------#

# user account
user:
    resource: "@UserBundle/Controller/"
    type: annotation
    prefix: /account
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}
    host: "{subdomain}.{domain_name}.{domain_ext}"

#------------------------------------------#
#                  FosUser                 #
#------------------------------------------#

# login withoute locale
fos_user_security_:
   path: /login
   host: "{subdomain}.{domain_name}.{domain_ext}"
   defaults:  { _controller: 'FOSUserBundle:Security:login' }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/
    requirements:
        _locale: '%locale_possible%'
    host: "{subdomain}.{domain_name}.{domain_ext}"
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: '%locale_possible%'
    host: "{subdomain}.{domain_name}.{domain_ext}"
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    host: "{subdomain}.{domain_name}.{domain_ext}"
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account/profile
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account/profile
    host: "{subdomain}.{domain_name}.{domain_ext}"
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}

#end user account

#------------------------------------------#
#                  Admin                   #
#------------------------------------------#

admin:
    resource: "@AdminBundle/Controller/"
    type: annotation
    prefix: /admin
    host: "{subdomain}.{domain_name}.{domain_ext}"
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}

# static translations
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix: /admin/translations
    host: "{subdomain}.{domain_name}.{domain_ext}"
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}

#------------------------------------------#
#              Other Resources             #
#------------------------------------------#

# images thumbmails
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# calendar
adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
