# sitemap
# https://github.com/prestaconcept/PrestaSitemapBundle/issues/101
# PrestaSitemapBundle:
#     resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
#     prefix:   /

#------------------------------------------#
#                Main page                 #
#------------------------------------------#

landing_page:
    resource: "@LandingPageBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}
    host:     "{domain_name}.{domain_ext}"
    # options:
    #     sitemap:
    #         priority: 0.7
    #         changefreq: weekly

#------------------------------------------#
#         Single project homepage          #
#------------------------------------------#

# main page resources
homepage_locale:
    path: /
    defaults:  { _controller: 'SiteBundle:Homepage:index', _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}
    host:     "{subdomain}.{domain_name}.{domain_ext}"
    # options:
    #     sitemap:
    #         priority: 0.7
    #         changefreq: weekly

site_content:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: '%locale_possible%'
    defaults: { _locale: '%locale%', domain_name: '%domain_name%', domain_ext: '%domain_ext%'}
    host:     "{subdomain}.{domain_name}.{domain_ext}"
    # options:
    #     sitemap:
    #         priority: 0.7
    #         changefreq: weekly
#------------------------------------------#
#                  User                    #
#------------------------------------------#

# user account
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /account

#fos user
fos_user_security_locale:
  path: /login
  defaults:  { _controller: 'FOSUserBundle:Security:login' }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /
    requirements:
        _locale: '%locale_possible%'

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /account/profile
    requirements:
        _locale: '%locale_possible%'

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register
    requirements:
        _locale: '%locale_possible%'

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    requirements:
        _locale: '%locale_possible%'

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account/profile
    requirements:
        _locale: '%locale_possible%'

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register
#     requirements:
#         _locale: '%locale_possible%'

# begin register routes

#custom register route
# fos_user_registration_register:
#     path: /register
#     methods: [GET, POST]
#     defaults:  { _controller: 'AccountFosUserBundle:Registration:register', _locale: '%locale%' }
#     requirements:
#         _locale: '%locale_possible%'

# fos_user_registration_check_email:
#     path: /register/check-email
#     methods: GET
#     defaults:  { _controller: 'FOSUserBundle:Registration:checkEmail', _locale: '%locale%' }
#     requirements:
#         _locale: '%locale_possible%'

# fos_user_registration_confirm:
#     path: /register/confirm/{token}
#     methods: [GET, POST]
#     defaults:  { _controller: 'FOSUserBundle:Registration:confirm', _locale: '%locale%' }
#     requirements:
#         _locale: '%locale_possible%'

# fos_user_registration_confirmed:
#     prefix: /register
#     path: /register/confirmed
#     methods: GET
#     defaults:  { _controller: 'FOSUserBundle:Registration:confirmed', _locale: '%locale%' }
#     requirements:
#         _locale: '%locale_possible%'

#end register routes

#end user account

#------------------------------------------#
#                  Admin                   #
#------------------------------------------#
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

# images thumbmails
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# calendar
adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
