  # To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512 # @TODO migrate to bcrypt
        # If your users have a password, then we recommend encoding it using the bcrypt encoder, instead of the traditional SHA-512 hashing encoder. The main advantages of bcrypt are the inclusion of a salt value to protect against rainbow table attacks, and its adaptive nature, which allows to make it slower to remain resistant to brute-force search attacks.
        # FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_MENTEE: ROLE_USER
        ROLE_MENTOR: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_TRANSLATOR: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            # id: fos_user.user_provider.username
            # fosu walkaround - email is the same as username
            id: fos_user.user_provider.username_email

    # https://symfony.com/doc/current/best_practices/security.html
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|img|js)/
            security: false
        # Unless you have two legitimately different authentication systems and users (e.g. form login for the main site and a token system for your API only), we recommend having only one firewall entry with the anonymous key enabled.
        main:
            # regexp that redirect to login page on this firewall
            # pattern: ^/((en|pl)/)?(account|admin)
            pattern: ^/
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous: true # you should use the anonymous key under your firewall
            form_login:
                provider: fos_userbundle
                default_target_path: account
                check_path: fos_user_security_check
            logout_on_user_change: true

    # https://symfony.com/doc/current/security/access_control.html
    access_control:
        # - { path: '^/((en|pl)/?)?account/login', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/account', role: ROLE_USER }
        - { path: '^/', role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: '^/media/cache/resolve/', role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: '.%domain_name%.%domain_ext%', role: IS_AUTHENTICATED_ANONYMOUSLY }
