# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
# parameters:
  # knp.doctrine_behaviors.translatable_subscriber.default_locale_callable.class: AppBundle\EventListener\LocaleCallable

services:
  # New in Symfony 3.3: Simpler service configuration
  # _defaults:
  #   autowire: true
  # _instanceof:
  #   # Add tag to all services defined in this file having this type
  #   Symfony\Component\EventDispatcher\EventSubscriberInterface:
  #     tags: ['kernel.event_subscriber']

  # truncate, wordwrap
  twig.extension.text:
   class: Twig_Extensions_Extension_Text
   tags:
      - { name: twig.extension }
  # shuffle
  twig.extension.array:
    class: Twig_Extensions_Extension_Array
    tags:
      - { name: twig.extension }

  organization.doctrine.filter.configurator:
    class: Repository\Filter\Configurator
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.request , priority: -10}

  organization.doctrine.listener.persister:
      class: Repository\EventListener\OrganizationPersister
      autowire: true
      tags:
        - { name: doctrine.event_listener, event: prePersist , priority: -100}
