# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  # knp.doctrine_behaviors.translatable_subscriber.default_locale_callable.class: AppBundle\EventListener\LocaleCallable

services:
  # truncate, wordwrap
  twig.extension.text:
   class: Twig_Extensions_Extension_Text
   tags:
      - { name: twig.extension }
  # shuffle
  twig.extension.array:
    class: Twig_Extensions_Extension_Array
    tags:
      - { name: twig.extension }

  organization.doctrine.filter.configurator:
    class: Repository\Filter\Configurator
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@annotation_reader'
        - '@subdomain.detection'
    tags:
        - { name: kernel.event_listener, event: kernel.request , priority: -10}

  organization.doctrine.listener.persister:
        class: Repository\EventListener\OrganizationPersister
        arguments:
            - '@annotation_reader'
            - '@subdomain.detection'
        tags:
            - { name: doctrine.event_listener, event: prePersist , priority: -100}
