# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # - 'form/form_theme.html.twig'
        - 'bootstrap_3_layout.html.twig'
        - 'SiteBundle:form:vich_form_theme.html.twig'

    globals:
        pathToWeb: "%kernel.root_dir%/../web"

    # https://symfony.com/doc/current/templating/namespaced_paths.html
    # Registering your own Namespaces
    # As an added bonus, the namespaced syntax is faster.
    # paths:
        # "%kernel.root_dir%/../src/Bundle/AdminBundle/Resources/views/mentee": Mentee
