services:

  dates.twig.extension:
    class: AdminBundle\Twig\EditionExtension
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@subdomain.detection'
    tags:
      - { name: twig.extension }

  program.excel.export:
    class: AdminBundle\Service\ExcelExport
    arguments:
      - '@phpexcel'
      - '@translator.default'
      - '@doctrine.orm.entity_manager'

  log.twig.extension:
    class: AdminBundle\Twig\PhotoInfoExtension
    tags:
      - { name: twig.extension }

  annotation.event_listener.users_accounts:
    class: AdminBundle\Security\Annotation\Listener\SectionEnabledAnnotationListener
    autowire: true
    tags:
        - { name: kernel.event_listener, event: kernel.controller }
